#!/bin/bash -eu

ROOT_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

pushd "${ROOT_DIRECTORY}"
  set -e
  docker build --tag=cfinfrastructure/gomegamatchers ${DOCKERFILE:-"${GOPATH}/src/github.com/cloudfoundry/mega-ci/dockerfiles/gomegamatchers"}
  docker run -v $PWD:/gomegamatchers -v ${MEGA_CI:-"${GOPATH}/src/github.com/cloudfoundry/mega-ci"}:/mega-ci cfinfrastructure/gomegamatchers ${TEST_TASK:-"/mega-ci/scripts/ci/gomegamatchers/test"}
popd
